import Head from "next/head"
import { Geist, Geist_Mono } from "next/font/google"
import styles from "@styles/landing.module.scss"

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
})

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
})

export default function Home() {
  return (
    <>
      <Head>
        <title>Card Deck</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div
        className={`${styles.root} ${geistSans.variable} ${geistMono.variable}`}
      >
        <main></main>
      </div>
    </>
  )
}
